### ISSUE TITLE
Chain upgrade requirements for Hermes (meta issue)

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#1209]
**!! This issue is currently a WIP !!**

## Crate

`ibc-relayer`

## Summary

Hermes requires some additional features to make chain upgrades more user-friendly.

Briefly, three features would be good to have:

- [ ] backwards compatiblity
    - switch between `/cosmos.upgrade.v1beta1.SoftwareUpgradeProposal` and `/ibc.core.client.v1.UpgradeProposal` at runtime, based on a `--legacy` flag passed to the `tx raw upgrade chain` CLI
- [ ] automatic client upgrade
    - listen and parse `newBlockEvents` to catch the `upgraded consensus state` event, and react on that by upgrading all counterparty clients
- [ ] correct client latest height upon chain id revision change

These will be further documented in their own issue.

## Problem Definition

The current workflow for upgrading a chain is:

1. submit chain upgrade proposal (either via hermes `upgrade-chain` or `gaiad`)
    - if the chain is on SDK 0.42.*, use Hermes (v0.6.0 works) 
2. use Hermes to upgrade counterparty clients of all other chains (using #763)

If the chain is using SDK 0.43, we are now adding support for it (#948) but that should be backwards compatible with 0.42, so that users can use the same Hermes version to do chain upgrades regardless of the minor version; that is the first feature above.

Having the second feature "automatic client upgrade" will simplify the workflow and make the process more smooth. With this feature, Hermes will react on a specific event of the upgrading chain and trigger counterparty client upgrades.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Sharing context here from a discussion in our IBC weekly call: 

> - ideal timeline: anytime before ibc clients will need to be upgraded
> - IBC clients on mainnets will need to undergo an upgrade because the IAVL in the SDK is abandoned → proof specs need to be updated (which the client stores)
>    - Chains doing the upgrade will store the new proof spec (client's 'upgrade_path')
