### ISSUE TITLE
Tracking issue for verification functions of TendermintClient

### ISSUE THREAD

**Issue by yito88** [informalsystems/ibc-rs#1214]
## Crate
IBC

## Summary of Bug
Almost all verification functions in `ibc::ics07_tendermint::client_def::TendermintClient` are not implemented.

## Version
0.6.0

## Steps to Reproduce
Call verification functions such as `ibc::ics03_connection::handler::verify::verify_proofs` with a TendermintClient

## Acceptance Criteria
All verification functions are implemented

- [x] #1452
- [ ] `verify_client_consensus_state`
- [ ] `verify_connection_state`
- [ ] `verify_channel_state`
- [ ] `verify_client_full_state`
____

## For Admin Use

- [X] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Just a note on progress on this PR: we are on it #1120. It should be done by the end of this milestone (end of July).

**Comment by lightyear15** [comment]
Hello,
I have been following the hermes project quite closely, taking it as a starting point for a non-cosmos-chain project. [see this](https://github.com/informalsystems/ibc-rs/issues/1481).
I am taking this issue as an ice-breaker to ask a few questions: 
- What is the purpose of the ``ClientDef`` trait and their implementation? 
- Isn't verifying states a duty that the client itself is in charge of, not something the relayer should bother about?
- in light of the recently approved new spec document on [wasm-based clients](https://github.com/cosmos/ibc/tree/master/spec/client/ics-008-wasm-client), how will the hermes realyer implementation for this new client type be able to fulfill the requirements for this a trait? (TL;DR for the wasm client: the client is implemented in wasm and runs in the cosmos chain as a smart contract, the ibc-go go module is an opaque sub-module that works as a proxy, forwarding all the client functions calls to the smart contract) How can the ``ics08-wasm`` module provides an implementation of ``ClientDef``?

Thanks

**Comment by adizere** [comment]
Hey, the `ClientDef` trait can be difficult to understand because this trait is a central interface between off-chain (relayer) and on-chain (modules) IBC components. Our repository comprises both on- and off-chain implementations, hence it's not always clear what's essential for the IBC relayer, and what pertains to the IBC module.

> What is the purpose of the ClientDef trait and their implementation?

The purpose is to capture all the methods that any IBC client implementation must provide. In other words, `ClientDef` is almost a 1:1 mapping of the [ICS02](https://github.com/cosmos/ibc/tree/master/spec/core/ics-002-client-semantics#consensusstate) specification.

All of the following components belong to our ibc module (on-chain) implementation:
- [`pub trait ClientDef`](https://github.com/informalsystems/ibc-rs/blob/52e0314050b5e984b740968fd90daaad83b5358e/modules/src/core/ics02_client/client_def.rs#L24)
- [`impl ClientDef for TendermintClient`](https://github.com/informalsystems/ibc-rs/blob/52e0314050b5e984b740968fd90daaad83b5358e/modules/src/clients/ics07_tendermint/client_def.rs#L45)
    - the specific implementation of ICS02 client for tendermint-specific chains, comprising all the verification predicates to semantically verify headers of a TM chain;
    - briefly, this is our implementation of the [ICS07 spec](https://github.com/cosmos/ibc/tree/master/spec/client/ics-007-tendermint-client).
- [`impl ClientDef for MockClient`](https://github.com/informalsystems/ibc-rs/blob/52e0314050b5e984b740968fd90daaad83b5358e/modules/src/mock/client_def.rs#L25)
    - an implementation of ICS02 for mock chains, which we use internally for testing
- [`impl ClientDef for AnyClient`](https://github.com/informalsystems/ibc-rs/blob/52e0314050b5e984b740968fd90daaad83b5358e/modules/src/core/ics02_client/client_def.rs#L173)
    - scaffolding to route between the trait and its different implementation
    - a valuable resource to understand more about this is [ADR 003](https://github.com/informalsystems/ibc-rs/blob/master/docs/architecture/adr-003-handler-implementation.md#dealing-with-chain-specific-datatypes).

> Isn't verifying states a duty that the client itself is in charge of, not something the relayer should bother about?


The off-chain IBC component (the relayer, i.e., Hermes) imports and uses all of these different types and methods because the relayer itself must perform header verification (which is a method that clients provide) for all the chains it communicates with. Hermes must verify states for several basic purposes:
1. to be able to fetch, deserialize, **syntactically** validate headers from a chain
    - and then construct client update transactions based on these headers, which the relayer submits to the counterparty chain
    - the functionality of updating clients is an essential pre-requisite for transfering packets (such as ICS20 token transfer packets).
2. to **semantically** verify headers and avoid submitting fraudulent headers in client update transactions (these transactions would be rejected, potentially wasting fees, and is in effect a sign of faulty behavior)
2. to run misbehavior detection (which is optional, most relayer implementations do not support this, but Hermes does).

> how will the hermes realyer implementation for this new client type be able to fulfill the requirements for this a trait?

Briefly, in order to support WASM clients for Hermes, it is essential to add the following components:
- `pub struct WasmClient` comprising the verification predicates that this client must implement to verify Wasm-chains.
- `impl ClientDef for WasmClient` comprising method forwarding between ICS02 interface and the verification predicates in `struct WasmClient`.

**Comment by lightyear15** [comment]
thanks @adizere for your explanation.
The very last point of your post is still very hard to digest for me.
To my knowledge, the whole idea of a wasm-based client is to remove from the on-chain IBC module the need for functions and algorithms necessary to understand and verify any consensus mechanisms used in non-tendermint chains.
So in my head, your statement  
> Briefly, in order to support WASM clients for Hermes, it is essential to add the following components:
> -  pub struct WasmClient comprising the verification predicates that this client must implement to verify Wasm-chains.
> - impl ClientDef for WasmClient comprising method forwarding between ICS02 interface and the verification predicates in struct WasmClient.

conflicts with the idea of having a complete transparent wasmclient proxy in the ibc-go module that simply forwards all the calls to a smart contract. You can have a look at a first implementation draft [here](https://github.com/cosmos/ibc-go/pull/208).
For instance, if you look at the implementation of the ``ClientState`` interface for ics08-wasm [here](https://github.com/cosmos/ibc-go/blob/7ae0507a974c8b7532d4ccf9ee697e8926cb608e/modules/light-clients/10-wasm/types/client_state.go) ), you can see that the module itself does not contain any logic about proofs verification, it simply forwards calls to the given smart contract.
My conclusion is then:
- I accept the idea of implementing an on-chain ics08-wasm component in here just to mirror the ( yet to be merged) implementation in cosmos/ibc-go repo, ( even though I see quite a few obstacles along this path as there is no cosmos-sdk implementation in rust, so I am not sure how I would deal with VM and smart contract calls)
-  I can't picture in my mind a feasible implementation of ``ClientDef`` for ``WasmClient`` that can fit into the relayer, unless we accept the idea that, when dealing with ics08-wasm clients  we have to delegate the verification and misbehavior detection to and only to the clients (resulting in an empty ``impl ClientDef for WasmClient`` implementation ).

As last point: I would argue that the relayer is not in charge of verifying anything as this is a duty the light-clients are in charge of, misbehaviour detection included. Otherwise IBC protocol wouldn't be a "mechanism to create trust-less bridges" but yet another trusted bridge protocol, as you are now relaying on the relayer (sorry for the pun) to pass truthful messages. 
Regarding the wast of fees when submitting fraudulent headers or, more in general, messages: I think it's up to the malicious actor to pay for the fees in the attempt to corrupt the client. As long as the benevolent relayer is connected to benevolent nodes of the two networks, gathering correct headers, it shouldn't be worried about fraudulent attacks made by malicious relayers trying to break the bridge. Of course, ibc modules and light clients running on the two chains must be robust enough to resist against any sort of attack.

**Comment by lightyear15** [comment]
Hi @adizere ,
any update on this on how the ``ics08-wasm`` could provide the ``verify_XXX`` functions when compiling the hermes binary?

**Comment by adizere** [comment]
> Hi @adizere ,
> any update on this on how the `ics08-wasm` could provide the `verify_XXX` functions when compiling the hermes binary?

Continued the discussion here: https://github.com/informalsystems/ibc-rs/discussions/1318#discussioncomment-1681566

**Comment by romac** [comment]
@lightyear15 I just want to point out that the plan for supporting WASM clients is indeed to call into the WASM code rather than hardcode anything in the `ClientDef` impl for `WasmClient`. More thought and investigate work is needed to figure out how to do this properly and whether or not the current `ChainEndpoint` + `ClientDef` traits are suitable for this purpose. We'll come back to you with a better plan once we get around to dedicate time to work on that. In the meantime, we're happy to hear any suggestions or feedback you may have for us :)

**Comment by lightyear15** [comment]
Hi @romac ,
thanks for your help.
I already have an almost-working implementation of wasm client based on hermes 0.7.2.
Happy to discuss the issues and struggles I went through :smile:

**Comment by romac** [comment]
@lightyear15 Oh wow, that's amazing 🎉 Yeah we would definitely love to hear about all that! Would be so kind as to (eventually) open a PR here?
