### ISSUE TITLE
Release Hermes v0.6.1

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#1224]
⚡

## Release PR

- [ ] #1226 

## Tasks

- [x] Create new release section in CHANGELOG and move "unreleased" items into this section.
- [x] Bump all crate versions to the new version.
- [ ] Reassign unfinished issues of previous milestone to the next milestone.
- [x] Update Cargo.lock file (if re-publishing `ibc-relayer-cli`)
