### ISSUE TITLE
Test the connection delay feature [meta]

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#1836]
## Summary

In preparation for extensive use in production, we would like to test that the Hermes connection delay functionality works as expected. This is a meta-issue to track the efforts on that front

## Acceptance Criteria

- [ ] write an automated test to exercise and assert the correctness of packet delays on a connection that has non-zero delay. 

Related issues tracked separately:
- [ ] #1772 
- [ ] #1773 

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned
