### ISSUE TITLE
Follow-up on message processor (handler) implementations

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#218]
## Summary of Bug

As a follow-up to #160, the short term plan for maturing the handlers is sketched below, in the order of their priority.

- [x] Wrap-up the work for #160 (PR #188) as soon as possible
(Anca, Romain, Adi)
- [x] Align testing across the handlers of ICS02 and ICS03; tentative strategy: test `process` as well as `keep` separately, then test `dispatch` by comparing its output to the ones of `process` and `keep`.
(primarily Romain) -> deferred to #269 
- [x] Adapt handlers to newer protobuf definitions, which include client state in the Try message
(primarily Anca) -- #226 
- [x] Extend ICS02 client mock to permit multiple consensus states, and two client states, thus reflecting more realistic testing scenarios
(primarily Adi) -- #221 
- [x] Cleanup Any* related code
(Romain) -- #225 
- [x] Finish all ICS03 messages: Ack and Confirm left (Adi) -- #223
- [X] Finish all ICS02/ ICS07/ mock message processing (ICS02 done with #270, ICS07 deferred to later)
- [x] Investigate whether we can replace `TryFromRaw` with the more standard `TryFrom`, with the goal of removing the former, see e.g., ICS 03 msgs.rs
(Adi) -- this was made obsolete by Greg's #252 

We'll expand and document each point (except for the first one) in a separate full-fledged issue as needed.

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
