### ISSUE TITLE
Release Hermes v1.0.0-rc.2

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#2521]
# Release Hermes v1.0.0-rc.2

## TODO

- [x] Add changelog entry for #2508
- [x] Remove tutorial using raw commands from the guide

⚡

- [ ] Create a new release in the changelog, using [`unclog`](https://github.com/informalsystems/unclog).
  - If doing a release candidate (`rc`) version, then skip the `unclog release` step.
- [x] Bump all crate versions to the new version.
- [x] Reassign unfinished issues of previous milestone to the next milestone.
- [x] Update Cargo.lock file (if re-publishing `ibc-relayer-cli`)
