### ISSUE TITLE
Compatibility with Cosmos SDK 0.46

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#2532]
## Summary

Ensure Hermes is compatible with chains based on Cosmos SDK 0.46.

## TODO

- [ ] Generate Protobufs from Cosmos SDK 0.46 and the corresponding IBC-Go version
- [ ] Bump compatibility check
- [ ] #2350 

## Acceptance Criteria

Hermes can relay without issue between chains based on Cosmos SDK 0.46

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
