### ISSUE TITLE
Review various TODOs in the code

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#2545]
## TODOs

- [ ] https://github.com/informalsystems/ibc-rs/blob/891d3f621a31d33894c20c19c518dd7910d7f8ed/relayer/src/chain/cosmos.rs#L685-L687
- [ ] https://github.com/informalsystems/ibc-rs/blob/891d3f621a31d33894c20c19c518dd7910d7f8ed/relayer/src/chain/cosmos.rs#L314-L315
- [ ] https://github.com/informalsystems/ibc-rs/blob/891d3f621a31d33894c20c19c518dd7910d7f8ed/relayer/src/chain/cosmos.rs#L704-L705
- [ ] https://github.com/informalsystems/ibc-rs/blob/891d3f621a31d33894c20c19c518dd7910d7f8ed/relayer/src/foreign_client.rs#L1257-L1263

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
