### ISSUE TITLE
`config auto` improvements

### ISSUE THREAD

**Issue by AlianBenabdallah** [informalsystems/ibc-rs#2550]
## Summary

#2533 Introduces a new command to automatically generate a config file. This issue lists some possible improvements.

## TODO : 
- [ ] Estimate gas parameters. The command currently uses hardcoded values. (P-high)
- [ ] Read data from the latest valid commit. The command currently reads from a specific commit (P-high)
- [ ] Add a cache (P-low)
- [ ] Check the config file's correctness after being created (or just ask user to perform `config validate` ?)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
