### ISSUE TITLE
Follow up on proto changes after deduplication fixes

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#306]
## Summary

As a follow-up on #284 (and PR #292), there are some leftover problems to solve?

- [ ] `MsgConnectionOpenAck` includes a new field `counterparty_connection_id`. Some minimal changes were done to handle this as part of #292 but tests need to be added. Also, the test infrastructure here is very hard to follow, maybe some cleanup would be nice 
- [x] `MsgConnectionOpenInit` includes a new `version` field. Some minimal changes were done but tests need to be updated. Also the whole connection versioning will probably need to be inspected to make sure it confirms with latest ICS. (fixed in #451)
- [x] `MsgConnectionOpenTry` includes a new `previous_connection_id` field. This requires updates to the message handler's validation logic and new tests. (fixed in #451)
- [ ] tendermint `ClientState` has new fields `proof_specs` (will be handled in #469) and `upgrade_path` that are currently ignored (will be handled and tested in #357). 
- [ ] A new `MsgUpgradeClient` msg is defined and needs to be implemented (#357)
~~[ ] `MsgUpdateClient` has a new field `consensus_params` that needs to be consumed by current code base.~~
_removed in cosmos `v0.40.0-rc5`_
- [X] query commands fail for client, `type_url`s need to be updated, fixed in #309
- [x] Introduce a newtype for versions (fixed in #451)
____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
