### ISSUE TITLE
VDD for Connection Handshake [master issue]

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#33]
## Summary

The idea is to use a verification-based approach at all steps of the development cycle of [Connection Handshake](https://github.com/cosmos/ics/tree/master/spec/ics-003-connection-semantics).

## Problem Definition

The goal is to catch bugs, prevent security problems, and finally obtain a formally verified implementation of Connection Handshake. To do so, this feature aims to align the development of Connection Handshake with our VDD approach. For a high-level description of how we will achieve this alignment, see [VDD/#2](https://github.com/informalsystems/VDD/issues/2) and the [VDD/connection](https://github.com/informalsystems/VDD/blob/7953ebb323bad7b272466b15713a225a7a4f99e4/ibc/connection/connection-L1.md) write-up.

## Proposal

List of deliverables that we'll target to have in the current repository for the Connection Handshake problem:

- [x] L1: High level English specification of the problem -- #34 
- [x] L2: High-level English specification of system model -- #35
- [x] L2: English description of the protocol -- #36
- [x] L2: TLA+ specification of the protocol -- #4 
- [x] L2: TLA+ specification of properties -- handled in #4
- [ ] ~~L2: Abstract test scenarios~~ unclear if this is useful at this moment; will be addressed potentially in later work.

____

#### For Admin Use

- [x] Individual issues raised to track each subordinate deliverable
- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
