### ISSUE TITLE
Relayer v0 MVP

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#385]
# Next third: Relayer v0 MVP

How to read this admin issue:

- This supersedes and expands on #114 and #119.
- Issues assigned to [milestone v0.0.5](https://github.com/informalsystems/ibc-rs/milestone/10) have the highest priority.
- Issues are clustered by crate, and ordered bottom-up: starting from crate `ibc` (deepest in the stack), then `relayer` and `relayer-cli` last.
- This tracks work at least until Dec. 31 2020 (for two upcoming releases, [v0.0.5](https://github.com/informalsystems/ibc-rs/milestone/10) and [v0.0.6](https://github.com/informalsystems/ibc-rs/milestone/11)) -> __edit__ up to Jan 31st 2021 [v0.1.0](https://github.com/informalsystems/ibc-rs/milestone/7)
- Any issue labeled with [dependencies](https://github.com/informalsystems/ibc-rs/labels/dependencies) should ideally:
    - (1) detail the dependency, and
    - (2) clarify the expectations on upstream teams (e.g., tendermint-rs, cosmos/ics, sdk) _before starting work on the PR_.

## Work breakdown

The main short-term deliverable is #381, and on a medium term we target #216.
Like prior milestones, the primary goal here is to obtain an integration point between crate `ibc` and the relayer implementation, towards improving our testing.

### General, technical debt:

- [x] Upgrade all crates to at least version 0.1.0 #181
- [x] Follow-up to migration work #469 
- [x] Follow up on proto changes after deduplication fixes #306
- [x] Issues with Light Client verification for relayer v0 MVP #410
- [x] Migrate to stargate 6 #503

### ICS 04:

- [X] Channel messages & domain type serialization #315
- Packets, Ack, and Timeout
    - [X] Messages & domain type #95
- [x] channOpenInit handler #445

### IBC Module improvements:

- [x] Follow up on proto changes after deduplication fixes #306
- [x] Extract the type_url explicit strings into constants #254

### Protos and events:

- [x] ibc-proto: Add Cosmos SDK sources as a Git submodule #240

### Relayer queries

- [x] The list of queries tracked separately by #128.

### Relayer application

The relayer application follows the decomposition laid out in [ADR-004](docs/architecture/adr-004-relayer-domain-decomposition.md).

- Implementation of ADR-005 relayer concurrency, split across:
    - [X] Chain thread: Runtime implementation #330
    - [x] Link module #328
    - [x] Monitor/subscription #380
    - [x] Relayer v0 config executor implementation #382
    - [x] (Sink issue) Implement concurrency architecture #327
- Main thread logic:
    - [x] Implement query_header_at_height() #336
    - [X] Configuration and parameters #346
    - [X] Client lifecycle #376
    - [X] Connection lifecycle #377
    - [X] Channel lifecycle #378
    - [x] Packet events & relay #379
- Implement basic keystore for V0 testing
    - [X] Command to add a key to a configured chain in the relayer #363

### Relayer configuration:

- [x] Align relayer config file with the light client config #99

### Relayer CLI TX

The goal here is to add support for `relayer tx raw <command>` CLI for manipulating various IBC objects. These are valuable for testing & debugging. They also provide the building blocks for the relayer main thread.

ICS02 / Client lifecycle CLIs:
- [X] Client Create #207
- [X] Client Update #277

ICS03 / Connection open handshake CLIs:
- Tracked in #208 and decomposed into
    - [X] ConnOpenInit #206
    - [X] ConnOpenTry #358
    - [X] ConnOpenAck #359
    - [X] ConnOpenConfirm #360

ICS04 / Channel & Packet lifecycle CLIs:
- [X] MsgChannelOpenInit #371
- [X] MsgChannelOpenTry #372
- [X] MsgChannelOpenAck #373
- [X] MsgChannelOpenConfirm #374
- [X] MsgRecvPacket #443
- [X] MsgChannelCloseInit, MsgChannelCloseConfirm, MsgTransfer, MsgTimeout, MsgAcknowledgement

### Testing & debugging

- [x] Integration tests for IBC queries #32
- Automatic client updates
    - [X] Mock context should accommodate TM light blocks #389
    - [x] Local chain #158,
    - [x] Client ping pong against local chain #381,
- [x] Upgrade simapp files to run with latest simd #204

### Backlog:

Some issues that are very low priority, or will not be attempted altogether in v0:

- Channel handler implementation #316
- Packet handlers implementation #362
- Update Relayer ADR #67
- Investigate and clean the `validate_basic` method #94
- Introduce datagram domain type #288
- Modular logic for ICS3 Connection handshake protocol #92
- Extract mocks protos from the `ibc-proto` crate into the `ibc` crate #329
- Figure out a common format for IBC events #102
- Model-based testing for ICS02 via ICS26 #324
- Client Upgrade #357
- Where should the`trust_threshold` and `trusting_period` configuration params live? #356
- Error wrapping and conversion between modules #68

**Comment by ancazamfir** [comment]
All issues closed

**Comment by romac** [comment]
Wow. Amazing work, @ancazamfir and @adizere!
