### ISSUE TITLE
Relayer CLI UX improvements

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#523]
## Crate

relayer-cli

## Summary

Improve the `relayer-cli` User Experience (UX)

## Problem Definition

Current User Experience (UX) for the relayer-cli is missing a few things that might improve its adoption when released.

## Proposal
- [ ] #574 Cleanup the .md files in the repository
- [ ] #542 Relayer documentation
- [x] #540 Avoid panics for commands (e.g. `tx raw create-client` when light clients are not setup). Better handling of unwraps.
- [ ] ~~Add additional information to the description fields of commands~~ will move to next release
- [x] Should we rename the `relayer-cli` executable to something else e.g. `rrly` ?
- [x] Inconsistent form for queries vs Tx packet CLIs (let's look at this again after #547)
- [x]  #575 Specifying height in `rrly query packet commitments -h 3218 ... ` doesn't work 
- [x] #540 More consistent error handling. For example, updating a non-existing client results in a panic, but querying for a non-existing client returns an error. The commands are:
`rrly -c loop_config.toml tx raw update-client ibc-0 ibc-1 07-tendermint-X`
`rrly -c loop_config.toml query client state ibc-0 07-tendermint-X`
- [x] Cleanup output of CLIs (#536)
- [x] #540 Rename the `v-0` command to `start`
- [x] #521 
- [x] Query all clients, connections and channels in a given chain (#552, #553, #568)
___

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
[ ] inconsistent form for queries vs Tx packet CLIs
In the packet Tx CLIs we specify the parameters as they appear in the different packet definitions. The packets' source port and channel are the same in `MsgTransfer` and `Packet` struct included in `MsgRecvPacket`, `MsgTimeout` and `MsgAcknowledgement`. 
(Note: This is in contrast with the channel and connection handshake messages where the connection, port, channel IDs are the ones on the chain receiving the message.)

For example:

`rrly -c loop_config.toml tx raw packet-send ibc-0 ibc-1 transfer channel-0 9999 1000` 
sends a `MsgTransfer` to `ibc-0`

`rrly -c loop_config.toml tx raw packet-recv ibc-0 ibc-1 07-tendermint-0 07-tendermint-0 transfer transfer channel-0 channel-0` 
either sends a `MsgRecvPacket` to `ibc-1` or a `MsgTimeout` to `ibc-0` 

`rrly -c loop_config.toml tx raw packet-ack  ibc-0 ibc-1 07-tendermint-0 07-tendermint-0 transfer transfer channel-0 channel-0`
sends a `MsgAcknowledgement` to `ibc-0`

So in all Tx CLIs, the first chain-id (`ibc-0` in the examples) is the initial packet source chain and not the destination of the IBC packet message built by the CLI.

In the same time the packet query CLIs are kept in line with the other queries (e.g. connection, channel) where the first chain-id is the chain that is queried.

This can be confusing and at minimum we should do a better job explaining in documentation and CLI help. The packet queries could probably drop the second (source) chain ID and perform some queries to determine the counterpary chain. 

[ ] specifying height in `rrly query packet commitments -h 3218 ...` doesn't work as (currently) grpc queries do not take the height parameter. We should probably remove the `-h` option and verify/ fix all other CLIs.
(CLI example:
`rrly -c loop_config.toml query packet commitments ibc-0 transfer channel-0 -h 3218`)

**Comment by romac** [comment]
- [ ] Let's also rename the `v-0` command to `start`

**Comment by ancazamfir** [comment]
> * [ ]  Let's also rename the `v-0` command to `start`

Added this in the main description so we have a full list there as well.

**Comment by ancazamfir** [comment]
> So in all Tx CLIs, the first chain-id (ibc-0 in the examples) is the initial packet source chain and not the destination of the IBC packet message built by the CLI.

Just a note that I am changing this as part of #547

**Comment by ancazamfir** [comment]
Closing this as we have two issues opened for the documentation already and these are the only ones left here.
