### ISSUE TITLE
Release IBC-RS v0.1.0

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#551]
# Release IBC-RS v.0.1.0

⚡

Started this issue ahead of the upcoming release, to keep track of all the last-minute things we may want to fix:

- [x] ~~Should we move the `guide/` into `relayer-cli`? doesn't seem to fit as top-level directory~~ (no)
- [x] Clean up the top-level directory & readmes: 
    - [x] #598  remove outdated (e.g. disclaimer and releases section) and unnecessary info from the main readme;  instead of ["running the relayer" section](https://github.com/informalsystems/ibc-rs#running-the-relayer) in the main readme, we can remove that section and point to [relayer-cli/operating-instructions.md](https://github.com/informalsystems/ibc-rs/blob/master/relayer-cli/relayer_operation_instructions.md)
    - [x] move the dev-env and one-chain scripts to the `relayer-cli/scripts` directory
    - [x] ensure we have a canonical configuration .toml file that we reference everywhere (see also [this comment](https://github.com/informalsystems/ibc-rs/issues/542#issuecomment-763617555))
    - [x] the relayer_operation_instructions.md file is useful but long and tedious (feels like a brain dump); it would be ideal to have a table of contents there and give it a hierarchical structure
- [x] Fix for #181 and see the comments therein
- [x] Fix #410
~~- [ ] Close issue #216 (this was our "target" for relayer v0 even it was a outdated), we can close it with 0.1.0~~
(moved to a later milestone)
- [ ] Create new release section in [CHANGELOG](./CHANGELOG.md) and move "unreleased" items into this section.
- [x] Bump all crate versions to the new version. #181
- [x] Reassign unfinished issues of previous milestone to the next milestone.
- [x] Try to include the queries for all clients, all connections and all channels on a given chain. (#552, #553, #568)
- [x] Update `tendermint` release in `Cargo.toml`

**Comment by ancazamfir** [comment]
> the relayer_operation_instructions.md file is useful but long and tedious (feels like a brain dump); it would be ideal to have a table of contents there and give it a hierarchical structure

That file is a temporary buffer with up-to-date CLIs to be used for the new documentation that @andynog is working on.

**Comment by andynog** [comment]
Yes @ancazamfir the new documentation I'm working on will be more structured and have sections for each topic
