### ISSUE TITLE
[ICS27] Implement interchain accounts application

### ISSUE THREAD

**Issue by Farhad-Shabani** [informalsystems/ibc-rs#576]
## Background
This issue tracks the efforts towards implementing ICS27, which aims to add interchain accounts application into the IBC-rs.

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/ibc-proto-rs/issues/106
- [ ] https://github.com/cosmos/ibc-rs/issues/735
- [ ] https://github.com/cosmos/ibc-rs/issues/717
- [ ] https://github.com/cosmos/ibc-rs/issues/718
- [ ] https://github.com/cosmos/ibc-rs/issues/734
```

```[tasklist]
### Tasks
```
