### ISSUE TITLE
Reactive relayer architecture for packets relaying and channel/connection handshakes

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#764]
## Crate

`ibc-relayer`, `ibc-relayer-cli`

## Summary

> Follow-up to https://github.com/informalsystems/ibc-rs/pull/692, https://github.com/informalsystems/ibc-rs/pull/733, and https://github.com/informalsystems/ibc-rs/pull/742.

Turn the multi-chain spike into a proper system for event-driven relaying with automatic channel and connection handshakes.

## Problem Definition

The current multi-chain spike only performs relaying of packets for any of the paths defined in the configuration.
As such, channels and connection must already be opened for it to function properly.

A passive relayer should be entirely event-driven and should not require any configuration besides the chains it can connect to.
As such, the relayer architecture must be updated to allow performing channel and connection handshakes dynamically, in an event-driven fashion.

## Proposal

We need to flesh out the [proposed architecture](https://tinyurl.com/6u6hbwh6), notably by

- [x] Ensuring partial order on events is preserved (eg. NewBlock events are sent after Tx events)
- [x] Only instantiate a single supervisor for all chains (#862)
- [x] Add ability to discover existing paths and relay on all those (#867)
- [x] Allow client level workers, e.g. to prevent client state expiration by performing client updates, or to monitor for misbehaviour. (#786)
- [x] Allowing workers to both initiate and complete a connection handshake (#821)
- [x] Allowing workers to both initiate and complete a channel handshake (#822)

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
