### ISSUE TITLE
Client operations cf. ADR 006

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#773]
## Crate

`ibc-relayer-cli`

## Proposal

Toward improving user experience and simplifying the code-base, we'd like to retire some of the `tx raw` commands.
For client operations, these two CLIs are wrappers over tx raw commands:

- `hermes create client`
```rust
    /// Subcommand for creating a `client`
    #[options(help = "Create a new IBC client")]
    Client(TxCreateClientCmd),
```

- `hermes update client`

```rust
    /// Subcommand for updating a `client`
    #[options(help = "Update an IBC client")]
    Client(TxUpdateClientCmd),
```

The two commands `create client` and `update client` should not build on `TxUpdateClientCmd` and `TxCreateClientCmd`.

### Tasks

- [x] ~~to remove the code for `TxUpdateClientCmd` and `TxCreateClientCmd` and move most of that functionality in module `create.rs` and `update.rs`.~~
- [x] ~~additionally, we want to adopt the syntax laid-out in ADR 006, and start using the terminology "host chain" and "target chain" instead of "source" and "destination" chains when talking about IBC client.~~
- [x] Current hermes create client CLI creates a client using the per chain configuration. We should provide a way for the user to specify the security parameters for the client (either described via CLI options or maybe a .json or other type of file including the parameters)
    - tracked separately in #836 

Additionally, for the `update` method:
- [x] Since we know the client's chain once it is created, maybe make this one `hermes update client ibc-0 07-tendermint-0` ( instead of `hermes update client ibc-0 ibc-1 07-tendermint-0`). Can do in a different PR also. (_Originally posted by @ancazamfir in https://github.com/informalsystems/ibc-rs/pull/774#discussion_r602420456_)

____

#### For Admin Use

- [x] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned
