### ISSUE TITLE
Upgrade Tokio to its latest version if deps are compatible

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#916]
## Crate

`relayer`, `relayer-cli`

## Summary

Update Tokio to its latest version and see if we can pass around Tokio handles rather than the Arc-wrapped runtime.

## TODO

- [ ] Check that all deps which also depends on Tokio are up to date and compatible.

## Acceptance Criteria

The Tokio dependency is updated to its latest version.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
I think this is not longer applicable.
