### ISSUE TITLE
Issues after testing with informal tesnet and cosmoshub-4

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#994]
## Crate
relayer

## Summary
- [X] hermes started with two chain configuration takes 2-3 minutes to filter through all the hub channels and figure out it needs to handle only one. This needs optimization. (#998 )
- [x] hermes gives a lot of spurious error `warn` level logs about non-IBC events, these should be lowered to `trace` or removed (#991)
- [x] `hermes query clients` returns only the client IDs in lexicographic order which is not helpful (especially on the hub with hundreds of clients) . Also one has to query individual clients to determine the counterparty chain. We should allow filtering with a remote chain ID; if one is not specified display and order by chain ID (#992)

(many thanks to @ebuchman for ^)

## Acceptance Criteria
Fix all of the listed issues

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
